### ISSUE TITLE
認識箇所の画像出力について

### ISSUE THREAD

**Issue by skeleton66** [ndl-lab/ndlkotenocr-lite#3]
出力設定の追加ありがとうございます！
認識箇所の画像を出力するかの設定も保存していただけると助かります

**Comment by ndl-lab-staff** [comment]
認識箇所の画像出力の設定保存は、出力形式の選択と違ってモーダルを閉じるときに保存処理を走らせることができないので追加のルーチンを実装する必要があります。

コマンドライン版には引数で制御する機能を提供していることを踏まえると、実装の複雑性を上げてメンテナンスを困難にするほどのメリットはないと判断しますのですみませんが本件は棄却させてください。

どうぞよろしくお願いいたします。
